### ISSUE TITLE
invalid payload: json: unknown field "aws_access_key_id" 

### ISSUE THREAD

**Issue by troykinsella** [concourse/registry-image-resource#126]
I'm trying to push an image built from a custom task script to an ECR repository with the following pipeline configuration:

```
# no resource_types entry for registry-image; using built-in.

resources:
- name: foo
  type: registry-image
  source:
    repository: category/my-ecr-image-name
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    tag: something

jobs:
- name: publish
  plan:
  - task: build foo which produces foo-image volume
     ...
  - put: foo
    params:
      image: foo-image
```

The `put` step then fails with:
```
ERRO[0000] invalid payload: json: unknown field "aws_access_key_id" 
```

This doesn't immediately make sense to me as `aws_access_key_id` is a documented `source` attribute, and I can see that the Go struct defines it: https://github.com/concourse/registry-image-resource/blob/master/types.go#L31

What might I be doing wrong?

Concourse version: 5.8.0

**Comment by fenech** [comment]
I was having the same issue until I switched to the `dev` tag of the resource in my pipeline:

```yaml
resource_types:
  - name: registry-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      tag: dev
```
I didn't look into which version of the resource was being used by default, but the latest "release" of this repo is from back in November, so it's likely to be missing things that are in master.

**Comment by acarsercan** [comment]
Same issue here

**Comment by fenech** [comment]
@acarsercan like I said (https://github.com/concourse/registry-image-resource/issues/126#issuecomment-602576363), it's fixed in master, and you can use a more recent image by adding the custom resource type in your pipeline.

**Comment by markbaird** [comment]
The `latest` release [in DockerHub](https://hub.docker.com/layers/concourse/registry-image-resource/latest/images/sha256-b7bda80f20a3624cf6e7a48eaf1ef3f2edec6d5bafeae46b3496c28bc1438828?context=explore) is from March, and it still appears to have this issue. I'm also seeing this issue today even when I try the custom resource type as listed above:

 ```
resource_types:
   - name: registry-image
     type: registry-image
     source:
        repository: concourse/registry-image-resource
        tag: dev

resources:
  - name: my-image
    type: registry-image
    source:
      repository: ((ecr_repo))
      aws_secret_key_id: ((aws_access_key))
      aws_secret_access_key: ((aws_secret))
      debug: true

jobs:
- name: publish
  plan:
  - task: build image
     ...
  - put: my-image
    params:
          image: image/image.tar,
          additional_tags: version/version
``` 

So I think whatever the current `dev` tagged release is, which is [only about 7 days old](https://hub.docker.com/layers/concourse/registry-image-resource/dev/images/sha256-2e6af2ee7b10f4f969df6cbe6c7fff22742df46cdac9dff16582d16e50d10469?context=explore), it also has the bug.

**Comment by danyoungmusic93** [comment]
@fenech What exactly do you mean by adding the custom resource type in the pipeline? My pipeline looks just like @troykinsella 's and I'm having the same issue. 

I tried your suggestion of tagging to a specific release, but with no success. Any updates on this?

**Comment by vito** [comment]
The updated resource type will be available in v6.3 - we're aiming to ship today.
